# This workflow lints and compiles the project.

name: Lint and compile

# Runs on pull requests, pushes to main, and manual dispatch.
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - run: npm ci
    - run: npm run lint

  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - run: npm ci
    - run: npm run build
